---
- hosts: all
  tasks:
  - name: Install python-Scapy and dependencies
    apt: name={{ item }} update_cache=yes
    loop: ['python3-scapy', 'net-tools']
    become: yes

  - name: Adjust arp table
    command: arp -i enp0s8 -s 192.168.50.11 08:00:27:60:0c:50
    become: yes